# Generated by Django 3.0.4 on 2020-03-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationallocation',
            name='location_type',
            field=models.CharField(choices=[('state', 'State'), ('district', 'District'), ('block', 'Block'), ('city', 'City')], default='block', max_length=30),
        ),
    ]
