# Generated by Django 3.0.4 on 2020-03-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200328_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='lng',
        ),
        migrations.AddField(
            model_name='pincode',
            name='taluk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Taluk'),
        ),
        migrations.DeleteModel(
            name='PostalOffice',
        ),
        migrations.AddField(
            model_name='pincodelocation',
            name='pincode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Pincode'),
        ),
    ]
