# Generated by Django 3.0.4 on 2020-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200328_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='operational_locations',
        ),
        migrations.AddField(
            model_name='ngo',
            name='operational_districts',
            field=models.ManyToManyField(to='webapp.District'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='operational_states',
            field=models.ManyToManyField(to='webapp.State'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='operational_taluks',
            field=models.ManyToManyField(to='webapp.Taluk'),
        ),
        migrations.DeleteModel(
            name='OperationalLocation',
        ),
    ]
