# Generated by Django 3.0.4 on 2020-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200328_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='operational_level',
            field=models.CharField(choices=[('state', 'State'), ('district', 'District'), ('block', 'Block'), ('city', 'City'), ('taluk', 'Taluk/Tehsil'), ('other', 'Other')], max_length=50),
        ),
    ]
