# Generated by Django 3.0.4 on 2020-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200328_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
