# Generated by Django 3.0.4 on 2020-03-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200329_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='govt_programs_contributed_to',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='govt_programs_partnered_with',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='is_govt_funded',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='operational_taluks',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='staff_details',
        ),
    ]
