# Generated by Django 3.0.4 on 2020-03-30 11:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200329_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='work_area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('health', 'Health'), ('education', 'Education'), ('nutrition', 'Nutrition'), ('disability', 'Disability'), ('wash', 'WASH'), ('livelihoods', 'Livelihoods'), ('financial_services', 'Financial Services'), ('others', 'Others')], max_length=80, null=True),
        ),
    ]
