# Generated by Django 3.0.4 on 2020-04-01 17:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200401_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='staff_languages',
        ),
        migrations.AlterField(
            model_name='ngo',
            name='operational_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('state', 'State'), ('district', 'District'), ('block', 'Block'), ('city', 'City'), ('taluk', 'Taluk/Tehsil'), ('other', 'Other')], max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='special_needs_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('no', 'No, we do not work with any special needs group'), ('mental_illness', 'People with mental illness'), ('hearing_loss', 'People with hearing loss'), ('physical_disabilities', 'People with physical disabilities'), ('intellectual_disabilities', 'People with intellectual disabilities'), ('aids', 'People living with HIV/AIDS'), ('chronic_illness', 'People living with chronic illness such as cancer, heart ailments, are immune-compromised'), ('elderly', 'Elderly'), ('tribal_population', 'Tribal population'), ('rural_poor', 'Rural poor'), ('urban_poor', 'Urban poor'), ('migrant_labourers', 'Migrant labourers'), ('hospice_shelters', 'Hospice/homes/orphanages/shelters'), ('homeless', 'Homeless'), ('others', 'Others')], max_length=198, null=True),
        ),
    ]
