# Generated by Django 3.0.4 on 2020-04-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200401_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='medium_of_reach',
            field=models.CharField(choices=[('inperson', 'In Person Only'), ('remotely', 'Remote Only via phones'), ('remote_and_inperson', 'Both in Person & Remotely via phones')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='population_reach',
            field=models.IntegerField(default=0),
        ),
    ]
