# Generated by Django 3.0.4 on 2020-04-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20200406_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='operational_districts',
        ),
        migrations.AlterField(
            model_name='ngo',
            name='does_staff_use_phones',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='False'),
        ),
        migrations.CreateModel(
            name='NgoDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_reach', models.IntegerField(choices=[(1000, 'less than 1000 people'), (10000, '1000 to 10,000 people'), (50000, '10,000 to 50,000 people'), (100000, 'more than 50,000 people')])),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.District')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Ngo')),
            ],
        ),
    ]
