# Generated by Django 3.0.4 on 2020-04-10 05:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200409_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='special_needs_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('no', 'No, we do not work with any special needs group'), ('mental_illness', 'People with mental illness'), ('hearing_loss', 'People with hearing loss'), ('physical_disabilities', 'People with physical disabilities'), ('intellectual_disabilities', 'People with intellectual disabilities'), ('aids', 'People living with HIV/AIDS'), ('sex_workers', 'Sex Workers'), ('injective_drug_users', 'Injective Drug Users'), ('msm_and_trans', 'MSM and Trans People'), ('chronic_illness', 'People living with chronic illness such as cancer, heart ailments, are immune-compromised'), ('elderly', 'Elderly'), ('tribal_population', 'Tribal population'), ('rural_poor', 'Rural poor'), ('urban_poor', 'Urban poor'), ('migrant_labourers', 'Migrant labourers'), ('hospice_shelters', 'Hospice/homes/orphanages/shelters'), ('homeless', 'Homeless'), ('others', 'Others')], max_length=245, null=True),
        ),
        migrations.AlterField(
            model_name='ngodistrict',
            name='population_reach',
            field=models.IntegerField(choices=[(1000, 'less than 1000 people'), (10000, '1000 to 10,000 people'), (50000, '10,000 to 50,000 people'), (100000, 'more than 50,000 people')], default=''),
        ),
    ]
