# Generated by Django 3.0.4 on 2020-04-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200410_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ngo',
            name='operational_districts',
            field=models.ManyToManyField(blank=True, related_name='ngos', through='webapp.NgoDistrict', to='webapp.District'),
        ),
        migrations.AlterField(
            model_name='ngodistrict',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngo_districts', to='webapp.District'),
        ),
        migrations.AlterField(
            model_name='ngodistrict',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_districts', to='webapp.Ngo'),
        ),
        migrations.AlterField(
            model_name='ngodistrict',
            name='population_reach',
            field=models.IntegerField(choices=[(1000, 'less than 1000 people'), (10000, '1000 to 10,000 people'), (50000, '10,000 to 50,000 people'), (100000, 'more than 50,000 people')], default=''),
        ),
    ]
