# Generated by Django 3.0.4 on 2020-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20200420_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodistrict',
            name='population_reach',
            field=models.IntegerField(choices=[(1000, 'less than 1000 people'), (10000, '1000 to 10,000 people'), (50000, '10,000 to 50,000 people'), (100000, 'more than 50,000 people')], default=0),
        ),
    ]
